export enum Emoji {
    'redSquare' = '🟥',
    'orangeSquare' = '🟧',
    'yellowSquare' = '🟨',
    'greenSquare' = '🟩',
    'blueSquare' = '🟦',
    'whiteSquare' = '⬜',
    'blackSquare' = '⬛',
    'OK' = '👌',
    'heart' = '❤️',
    'eye' = '👁️',
    'paw' = '🐾',
    'ghost' = '👻',
    'alien' = '👽',
    'skull' = '💀',
    'unicorn' = '🦄',
    'brain' = '🧠',
    'HI' = '🖐️',
    'cart' = '🛒',
}
