"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Emoji = void 0;
var Emoji;
(function (Emoji) {
    Emoji["redSquare"] = "\uD83D\uDFE5";
    Emoji["orangeSquare"] = "\uD83D\uDFE7";
    Emoji["yellowSquare"] = "\uD83D\uDFE8";
    Emoji["greenSquare"] = "\uD83D\uDFE9";
    Emoji["blueSquare"] = "\uD83D\uDFE6";
    Emoji["whiteSquare"] = "\u2B1C";
    Emoji["blackSquare"] = "\u2B1B";
    Emoji["OK"] = "\uD83D\uDC4C";
    Emoji["heart"] = "\u2764\uFE0F";
    Emoji["eye"] = "\uD83D\uDC41\uFE0F";
    Emoji["paw"] = "\uD83D\uDC3E";
    Emoji["ghost"] = "\uD83D\uDC7B";
    Emoji["alien"] = "\uD83D\uDC7D";
    Emoji["skull"] = "\uD83D\uDC80";
    Emoji["unicorn"] = "\uD83E\uDD84";
    Emoji["brain"] = "\uD83E\uDDE0";
    Emoji["HI"] = "\uD83D\uDD90\uFE0F";
    Emoji["cart"] = "\uD83D\uDED2";
})(Emoji = exports.Emoji || (exports.Emoji = {}));
